# (generated with --quick)

import flask.wrappers
from typing import Any, Dict, List

TradingAgent: Any
_ROOT: str
os: module
re: module
request: flask.wrappers.Request

class TradeHandler:
    def _delete_stop_order(self) -> Dict[str, List[Dict[str, str]]]: ...
    def _new_market_order(self) -> Dict[str, str]: ...
    def _new_stop_order(self) -> Dict[str, List[Dict[str, str]]]: ...
    def _read_stop_orders(self) -> Dict[str, List[Dict[str, str]]]: ...
    def _statistic(self) -> Dict[str, str]: ...
    def response_order(self) -> Any: ...
    def response_statistic(self) -> Any: ...
